export type SessionKind = 'Lecture' | 'Lecture MCQ' | 'Practical' | 'Final Mock';

export interface AssessmentQuestion {
  prompt: string;
  choices: string[];
  answer: string;
}

export interface CourseSession {
  kind: SessionKind;
  number: number;
  title: string;
  topic: string;
  objective: string;
  content: string;
  questions: AssessmentQuestion[];
  codeScenario?: string;
  codeKeywords?: string[];
}

interface Lesson {
  title: string;
  objective: string;
  content: string;
  questions: AssessmentQuestion[];
}

interface SkillCourse {
  topics: [string, string];
  lessons: Lesson[];
  practicals: string[];
  finalMock: AssessmentQuestion[];
  codeKeywords: string[];
}

const question = (prompt: string, answer: string, wrong: string[]): AssessmentQuestion => ({ prompt, choices: [answer, ...wrong], answer });

const fallbackQuestions = (skill: string): AssessmentQuestion[] => [
  question(`What should you identify first when learning ${skill}?`, 'The problem, inputs, output, and constraints', ['Only advanced features', 'A random code sample', 'The screen layout']),
  question(`What makes ${skill} useful in a real project?`, 'A clear problem and repeatable process', ['Using every feature at once', 'Avoiding tests', 'Copying without understanding']),
  question(`What should a learner check after using ${skill}?`, 'Whether the result meets the requirement', ['Only the file name', 'The number of tabs open', 'Nothing']),
  question(`Which habit supports reliable ${skill} work?`, 'Small steps with checks', ['Large untested changes', 'Skipping documentation', 'Never reviewing output']),
  question(`How should a beginner improve at ${skill}?`, 'Practice, inspect results, and revise', ['Avoid feedback', 'Only watch introductions', 'Change tools every day'])
];

const fallbackLessonsGenerated = (skill: string): Lesson[] => [
  { title: `${skill} concepts`, objective: `Understand the foundations of ${skill}.`, content: `${skill} is used to solve a defined problem in a professional workflow. Begin by naming the problem, the inputs, the desired output, and the constraints. Precise vocabulary makes collaboration and debugging faster. A beginner should explain the main concepts before attempting a complex task.`, questions: fallbackQuestions(skill) },
  { title: `${skill} application`, objective: `Apply ${skill} carefully and verify the result.`, content: `Practical work with ${skill} becomes reliable when a large requirement is divided into small steps. Each step should produce an observable result that can be checked. Testing normal, empty, and boundary inputs reveals assumptions. When something fails, reproduce it, inspect the smallest useful example, change one thing, and run the check again.`, questions: fallbackQuestions(skill) }
];

const fallbackLessons = (skill: string): Lesson[] => [
  { title: `${skill} purpose and vocabulary`, objective: `Understand the language of ${skill}.`, content: `${skill} is used to solve a defined problem in a professional workflow. Begin by naming the problem, the inputs, the desired output, and the constraints. The vocabulary of a tool is important because precise names make collaboration and debugging faster. A beginner should be able to explain the purpose of the main concepts before attempting a complex task.`, questions: [question(`What should you identify first when learning ${skill}?`, 'The problem, inputs, output, and constraints', ['Only advanced features', 'A random code sample', 'The screen layout', 'Nothing']), question(`Why does ${skill} vocabulary matter?`, 'It makes communication and debugging more precise', ['It replaces testing', 'It removes requirements', 'It guarantees perfect code', 'It is only decorative']), question(`What is a good beginner target?`, 'Explain the main concepts before using advanced features', ['Skip all foundations', 'Memorize every API', 'Avoid examples', 'Only read job titles']), question(`What does a constraint describe?`, 'A limit or condition the solution must respect', ['A colour scheme', 'A file icon', 'A username', 'An empty result']), question(`What should a requirement include?`, 'A clear expected result', ['Only a tool name', 'No assumptions', 'An unrelated feature', 'A blank document'])] },
  { title: `${skill} application and testing`, objective: `Apply ${skill} carefully and verify the result.`, content: `Practical work with ${skill} becomes reliable when a large requirement is divided into small steps. Each step should produce an observable result that can be checked. Testing normal inputs, empty inputs, and boundary cases reveals assumptions that are easy to miss. When something fails, reproduce the failure, inspect the smallest useful example, change one thing, and run the check again.`, questions: [question(`What makes a ${skill} solution reliable?`, 'Small steps with observable checks', ['One huge untested change', 'No requirements', 'Changing tools constantly', 'Avoiding feedback']), question('Which cases should a beginner test?', 'Normal, empty, and boundary cases', ['Only the favourite example', 'No cases', 'Only invalid syntax', 'Only the largest input']), question('What is the first debugging action?', 'Reproduce the failure with a small example', ['Delete the code', 'Ignore the error', 'Rewrite everything', 'Remove the test']), question('Why split a requirement into steps?', 'It makes results and failures easier to inspect', ['It prevents learning', 'It hides assumptions', 'It removes outputs', 'It avoids all decisions']), question('When is a task ready to review?', 'When its result can be compared with the requirement', ['When it looks long', 'When no one can test it', 'When it has no output', 'When the deadline is close'])] }
];

const pythonLessons: Lesson[] = [
  { title: 'Python syntax and data', objective: 'Read and write the building blocks of Python.', content: 'Python programs are made from expressions, statements, variables, and values. A variable gives a meaningful name to data so the program can use that data more than once. Lists preserve an ordered collection, dictionaries connect keys to values, and strings represent text. Conditions choose a path, while loops repeat a path. Readable indentation is part of Python syntax, not decoration. Start with a small input and trace how each value changes as the program runs.', questions: [question('Which Python collection is ordered and mutable?', 'List', ['Tuple', 'String', 'Set']), question('What does a variable provide?', 'A name for a value', ['A database server', 'A required loop', 'A screen layout']), question('What do dictionaries store?', 'Key-value relationships', ['Only ordered text', 'Only functions', 'Only comments']), question('What does a loop do?', 'Repeats a block of logic', ['Deletes every value', 'Creates a monitor', 'Stops all conditions']), question('Why is indentation important in Python?', 'It defines code blocks', ['It changes the keyboard', 'It replaces data', 'It disables testing'])] },
  { title: 'Python functions and reuse', objective: 'Design small functions with clear inputs and outputs.', content: 'A function packages a repeatable operation behind a name. Parameters describe the information a function receives, and return values describe the result it gives back. Small functions are easier to read because each one has a focused responsibility. A useful function avoids hidden state where possible and handles invalid or empty input deliberately. Before combining several functions, test each one with a simple example so a failure has a narrow source.', questions: [question('Which keyword defines a Python function?', 'def', ['class', 'func', 'method']), question('What is a parameter?', 'An input accepted by a function', ['A printed result', 'A file extension', 'A loop error']), question('Why keep a function focused?', 'It is easier to reuse and test', ['It prevents all outputs', 'It makes names unnecessary', 'It hides every error']), question('What does return do?', 'Sends a result back to the caller', ['Starts a server', 'Deletes a parameter', 'Changes indentation']), question('What should happen with empty input?', 'The function should handle it intentionally', ['The case should be ignored', 'The program must always crash', 'The test should be deleted'])] },
  { title: 'Python control flow', objective: 'Use decisions and repetition to model a process.', content: 'Control flow determines the order in which instructions run. An if statement handles a decision, elif adds another condition, and else provides a fallback. A for loop is useful when visiting each item in a collection, while a while loop repeats until a condition changes. Off-by-one errors happen when a boundary is counted incorrectly. Trace the first, middle, and last values when checking a loop.', questions: [question('What does an if statement do?', 'Chooses a path based on a condition', ['Stores an image', 'Always repeats code', 'Creates a table']), question('When is a for loop useful?', 'When visiting items in a collection', ['When no values exist', 'Only for comments', 'Only for imports']), question('What causes an off-by-one error?', 'A boundary is included or excluded incorrectly', ['A variable has a name', 'A function returns', 'A test has an input']), question('What should a while loop change?', 'Its condition must eventually move toward completion', ['The monitor colour', 'The file icon', 'The keyboard layout']), question('Which values help trace a loop?', 'First, middle, and last values', ['Only the title', 'Only an empty value', 'No values'])] },
  { title: 'Python testing and debugging', objective: 'Use evidence to find and fix defects.', content: 'A test is a repeatable question about program behaviour. Arrange an input, act by calling the code, and assert the expected result. Good tests cover a normal case and the edges that might expose an assumption. A failing test is useful evidence, not merely a problem. Reproduce it, isolate the smallest failing input, inspect the values, make one focused change, and run the test again.', questions: [question('What does an assertion compare?', 'Actual behaviour with an expected result', ['Two screen colours', 'Two usernames', 'A file and a monitor']), question('Why test edge cases?', 'They expose assumptions at boundaries', ['They make code longer only', 'They remove requirements', 'They avoid all inputs']), question('What is a failing test?', 'Evidence that behaviour differs from expectation', ['A reason to delete tests', 'A successful release', 'An empty requirement']), question('Why isolate a failure?', 'It narrows the cause of the defect', ['It hides the output', 'It changes every variable', 'It avoids inspection']), question('What should you change during debugging?', 'One focused thing at a time', ['Every file at once', 'Nothing ever', 'Only the test name'])] },
  { title: 'Python collections and integration', objective: 'Combine Python parts into a useful solution.', content: 'Real tasks combine collections, functions, conditions, and tests. A list can be transformed with a loop, a dictionary can index information for quick lookup, and a function can expose the operation to the rest of the program. Integration means checking that parts agree on the shape and meaning of their data. Keep transformations explicit, name intermediate values, and add a test at the boundary where one function hands data to another.', questions: [question('What is integration?', 'Combining parts and checking their boundaries', ['Deleting all functions', 'Changing the editor theme', 'Avoiding inputs']), question('Why name intermediate values?', 'They make transformations easier to inspect', ['They remove outputs', 'They hide data', 'They replace tests']), question('What is a dictionary useful for?', 'Looking up values by keys', ['Only repeating text', 'Only storing comments', 'Only drawing charts']), question('What should a boundary test check?', 'The data passed between components', ['The screen resolution', 'The number of tabs', 'The logo size']), question('What makes integrated code maintainable?', 'Clear transformations and focused functions', ['Hidden state everywhere', 'No names', 'One giant expression'])] }
];

const sqlLessons: Lesson[] = [
  { title: 'SQL SELECT and filtering', objective: 'Read tables and retrieve the rows you need.', content: 'SQL is declarative: describe the result rather than a sequence of machine instructions. SELECT names the columns, FROM names the source table, and WHERE removes rows that do not meet a condition. Begin by inspecting the table columns and the data types. Use a small result while developing, then remove the limit only after the selected rows and filters make sense.', questions: [question('Which clause filters rows?', 'WHERE', ['GROUP BY', 'ORDER BY', 'VALUES']), question('What does SELECT choose?', 'Columns in the result', ['Only database users', 'Only chart colours', 'Only comments']), question('Why inspect data types?', 'To write correct comparisons and transformations', ['To avoid all queries', 'To rename the database', 'To remove tables']), question('What does FROM identify?', 'The table or source of rows', ['The output colour', 'The user password', 'The test runner']), question('Why use a small result while developing?', 'It makes the result easier to inspect', ['It changes the schema', 'It avoids filtering', 'It deletes records'])] },
  { title: 'SQL grouping and aggregates', objective: 'Summarise records into useful measures.', content: 'Aggregate functions calculate values across rows. COUNT measures records, SUM adds numeric values, AVG calculates a mean, and MIN or MAX find extremes. GROUP BY creates one result group for each category. A grouped query should be checked against a known total and should make its grain clear: one row per customer, order, product, or another stated unit.', questions: [question('Which clause creates categories for aggregates?', 'GROUP BY', ['WHERE', 'LIMIT', 'VALUES']), question('What does COUNT measure?', 'The number of records', ['The longest string', 'A table name', 'A join key']), question('Why define the grain?', 'It clarifies what one result row represents', ['It removes all rows', 'It hides duplicates', 'It changes SQL syntax']), question('What does SUM do?', 'Adds numeric values', ['Filters text', 'Joins users', 'Sorts columns']), question('What should a grouped result be checked against?', 'A known total or expected count', ['Only its colour', 'The editor width', 'No reference'])] },
  { title: 'SQL joins and relationships', objective: 'Combine related data without accidental duplicates.', content: 'A JOIN connects tables through related columns, usually a primary key and a foreign key. An inner join keeps matching rows, while a left join keeps every row from the left table even when no related row exists. The relationship cardinality matters: one customer can have many orders, so a join may intentionally produce several rows per customer. Check unmatched records and duplicates before trusting a report.', questions: [question('What does a JOIN connect?', 'Related tables through keys', ['Unrelated colours', 'Only comments', 'Two screen layouts']), question('What does a left join preserve?', 'Every row from the left table', ['Only unmatched right rows', 'No rows', 'Only duplicate rows']), question('Why can a join create duplicates?', 'One row may match many related rows', ['SQL cannot filter', 'Keys are always unique across tables', 'Comments repeat']), question('What should a join condition use?', 'The correct related columns', ['The table colour', 'A random number', 'The query title']), question('What should be checked after joining?', 'Matches, unmatched rows, and row counts', ['Only query length', 'No output', 'The keyboard'])] },
  { title: 'SQL NULLs and validation', objective: 'Handle missing data and verify query correctness.', content: 'NULL means a value is unknown or missing; it is not the same as zero or an empty string. Comparisons with NULL require IS NULL or IS NOT NULL. Reports should make their treatment of missing data explicit. Validation includes checking row counts, duplicate keys, expected totals, and sample records. These checks turn a query that merely runs into analysis that can be trusted.', questions: [question('How do you check for missing SQL values?', 'IS NULL or IS NOT NULL', ['= EMPTY', 'MISSING()', 'HAS VALUE']), question('Is NULL equal to zero?', 'No, NULL represents unknown or missing data', ['Yes always', 'Only in joins', 'Only in text']), question('Why validate row counts?', 'To detect missing or duplicated records', ['To change the editor', 'To avoid schemas', 'To hide results']), question('What should a report document?', 'How missing data is treated', ['Only its font', 'Nothing', 'Only the table colour']), question('What is a trustworthy query result?', 'One checked against requirements and data expectations', ['Any result that runs', 'A blank result', 'An untested guess'])] },
  { title: 'SQL reporting workflow', objective: 'Turn a business question into a checked query.', content: 'A reporting workflow starts with a precise question and a definition of the result grain. Identify the required tables, choose the relationships, filter the relevant period, calculate the measures, and inspect representative rows. Write the query in readable stages so another person can audit it. Before delivery, compare totals with a known source and record assumptions about missing or late data.', questions: [question('What starts a reporting workflow?', 'A precise question and result grain', ['A random table', 'A chart colour', 'An untested join']), question('Why write readable SQL stages?', 'Another person can audit the reasoning', ['It removes tables', 'It prevents filters', 'It hides assumptions']), question('What should happen before delivery?', 'Compare results with a known source', ['Delete the query', 'Skip validation', 'Change the question']), question('What are assumptions?', 'Decisions about data and missing cases', ['Only keyboard settings', 'Random outputs', 'Table colours']), question('What makes a report useful?', 'An accurate result tied to the business question', ['A long query only', 'No grain', 'No checks'])] }
];

function buildCourse(skill: string): SkillCourse {
  if (skill === 'Python') return { topics: ['Python foundations', 'Python problem solving'], lessons: pythonLessons, practicals: ['Write a function that counts words in a sentence.', 'Transform a list of numbers and return only valid values.', 'Debug a function with an off-by-one error.', 'Build a small command-line style menu.', 'Write tests for empty, normal, and boundary inputs.'], finalMock: fallbackQuestions('Python'), codeKeywords: ['def', 'return'] };
  if (skill === 'SQL') return { topics: ['SQL foundations', 'SQL analysis and testing'], lessons: sqlLessons, practicals: ['Write a filtered SELECT query for active records.', 'Group sales by category and calculate a total.', 'Find and fix a query that duplicates rows after a JOIN.', 'Combine customer and order tables for a report.', 'Write checks for empty results and unexpected NULL values.'], finalMock: fallbackQuestions('SQL'), codeKeywords: ['select', 'from'] };
  const fallback = fallbackLessons(skill);
  return { topics: [fallback[0].title, fallback[1].title], lessons: [...fallback, ...fallback, ...fallback, ...fallback, ...fallback], practicals: [`Create a small ${skill} solution for a clear requirement.`, `Extend the solution with a second input case.`, `Debug a failing ${skill} scenario.`, `Build a useful workplace example with ${skill}.`, `Write checks that prove the ${skill} result is correct.`], finalMock: fallbackQuestions(skill), codeKeywords: [skill.toLowerCase().split(' ')[0]] };
}

export function createCourseSessions(skill: string): CourseSession[] {
  const course = buildCourse(skill);
  const lectureLessons = Array.from({ length: 10 }, (_, index) => {
    const source = course.lessons[index % course.lessons.length];
    const cycle = index < course.lessons.length ? '' : ` This second pass deepens the topic through a new focus on ${index % 2 === 0 ? 'design decisions and trade-offs' : 'reviewing real output and edge cases'}.`;
    const beginnerGuide = `Beginner guide: Think of ${skill} like a recipe. The ingredients are the information you start with, the instructions are the steps you follow, and the finished dish is the result you want. You do not need a computer background for this lesson. Read one idea at a time, say it back in your own words, and look for one small example before moving on.`;
    const topicIntroduction = `Topic introduction: This lesson builds one part of ${skill} that appears in real ${skill} work. Start by asking what problem the idea solves, what information it needs, and what a useful result looks like. Connecting the topic to a concrete task makes the new vocabulary easier to remember.`;
    const practiceGuide = `Practical relevance: In a workplace, ${skill} is valuable when it produces a result that another person can understand, review, and use. Apply the idea to a small role-related example, inspect the output, and compare it with the original requirement. This habit turns a lesson into a dependable working skill.`;
    const takeaway = `Key takeaways: first identify the input and expected output; next describe the steps in plain language; finally check normal, empty, and boundary cases. These three checks are enough to begin confidently, while the technical terms give you precise language for discussing the solution with a team.`;
    return { ...source, title: index < course.lessons.length ? source.title : `${source.title} deep dive`, content: `${beginnerGuide}\n\n${topicIntroduction}\n\n${source.content}${cycle}\n\n${practiceGuide}\n\n${takeaway}` };
  });
  const sessions: CourseSession[] = [];
  lectureLessons.forEach((lesson, index) => {
    sessions.push({ kind: 'Lecture', number: sessions.length + 1, title: `Lecture ${index + 1}: ${lesson.title}`, topic: index < 5 ? course.topics[0] : course.topics[1], objective: lesson.objective, content: lesson.content, questions: lesson.questions });
    if (index === 2 || index === 5 || index === 8) {
      const practicalIndex = index === 2 ? 0 : index === 5 ? 1 : 2;
      const scenario = course.practicals[practicalIndex];
      sessions.push({ kind: 'Practical', number: sessions.length + 1, title: `Coding practical ${practicalIndex + 1}`, topic: 'Applied coding', objective: `Apply the previous three lectures in a ${skill} task.`, content: `Problem: ${scenario}\n\nExpected behavior: turn the requirement into a small, readable solution that produces the requested result for valid input and handles an empty or boundary case deliberately.\n\nExample: begin with one simple input, write down the expected output in plain language, then test a second input that could reveal an incorrect assumption.`, questions: [], codeScenario: scenario, codeKeywords: course.codeKeywords });
    }
  });
  const lectureQuestions = [lectureLessons[0], lectureLessons[1], lectureLessons[5], lectureLessons[6], lectureLessons[2]].map((lesson) => lesson.questions[0]);
  sessions.push({ kind: 'Lecture MCQ', number: sessions.length + 1, title: 'Lecture MCQ checkpoint', topic: 'Both lecture topics', objective: `Check understanding of the ${skill} lectures.`, content: 'Answer five questions based on the lecture material. Your mark out of five and efficiency percentage appear immediately after submission.', questions: lectureQuestions });
  course.practicals.slice(3).forEach((scenario, index) => sessions.push({ kind: 'Practical', number: sessions.length + 1, title: `Coding practical ${index + 4}`, topic: 'Applied coding', objective: `Complete an integrated ${skill} task.`, content: `Problem: ${scenario}\n\nExpected behavior: combine the earlier ideas into a solution that can be reviewed and tested. Make the input, output, and assumptions visible in your approach.\n\nExample: demonstrate the solution with one normal case and one edge case before you submit it.`, questions: [], codeScenario: scenario, codeKeywords: course.codeKeywords }));
  sessions.push({ kind: 'Final Mock', number: sessions.length + 1, title: 'Final course mock', topic: 'Full course review', objective: `Demonstrate complete ${skill} readiness.`, content: 'This final mock reviews the lecture topics and practical reasoning before the course certificate is awarded.', questions: course.finalMock });
  return sessions;
}

export function getEfficiency(score: number, total: number): number { return total === 0 ? 0 : Math.round((score / total) * 100); }

export function evaluateCode(code: string, keywords: string[] = []): boolean { const normalized = code.trim().toLowerCase(); return normalized.length >= 20 && keywords.some((keyword) => normalized.includes(keyword.toLowerCase())); }
