import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useState } from 'react';
import { api } from '../lib/api';
import { excelCompanyNames } from '../data/companies';

export default function Browse() {
  const [company, setCompany] = useState('');
  const [field, setField] = useState('');
  const [search, setSearch] = useState('');
  const companies = [...excelCompanyNames];
  const { data: roles = [], isLoading } = useQuery({ queryKey: ['roles', company, field, search], queryFn: () => api.roles(new URLSearchParams({ ...(company && { company }), ...(field && { field }), ...(search && { search }) }).toString()) });
  const fields = ['IT', 'Non-IT'] as const;
  return <main className="container-shell py-16"><div className="max-w-2xl"><p className="eyebrow">Role directory</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight">Find your next role to study.</h1><p className="mt-4 text-lg leading-8 text-slate-500">Choose an IT or Non-IT path, then filter by employer or role name.</p></div><div className="mt-10 grid gap-3 rounded-xl border border-slate-200 bg-mist p-4 md:grid-cols-[1fr_1fr_1.4fr]"><select aria-label="Filter by company" value={company} onChange={(event) => setCompany(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-4 py-3 text-base"><option value="">All companies</option>{companies.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter by field" value={field} onChange={(event) => setField(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-4 py-3 text-base"><option value="">All fields</option><option>IT</option><option>Non-IT</option></select><label className="flex items-center gap-3 rounded-lg border border-slate-200 bg-white px-4"><Search size={19} className="text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search role name" className="w-full bg-transparent py-3 text-base outline-none" /></label></div>{isLoading ? <p className="mt-10 text-slate-500">Loading roles...</p> : <div className="mt-10 space-y-10">{fields.map((roleField) => { const fieldRoles = roles.filter((item) => item.field === roleField); return <section key={roleField} aria-labelledby={`${roleField}-heading`}><div className="flex items-end justify-between border-b-2 border-pulse pb-4"><div><p className="eyebrow">Career path</p><h2 id={`${roleField}-heading`} className="mt-2 text-3xl font-extrabold">{roleField} roles</h2></div><span className="text-base text-slate-500">{fieldRoles.length} postings</span></div><div className="mt-4 overflow-hidden rounded-xl border border-slate-200"><div className="hidden grid-cols-[1.2fr_1fr_auto] gap-4 bg-mist px-5 py-3 text-xs font-bold uppercase tracking-wider text-slate-500 sm:grid"><span>Role</span><span>Company</span><span></span></div>{fieldRoles.map((item) => <Link to={`/roles/${item.id}`} key={item.id} className="grid gap-2 border-t border-slate-100 px-5 py-5 first:border-t-0 transition hover:bg-emerald-50 sm:grid-cols-[1.2fr_1fr_auto] sm:items-center sm:gap-4"><span className="text-lg font-bold">{item.role}</span><span className="text-base text-slate-600">{item.company}</span><ArrowRight className="hidden text-pulse sm:block" size={20} /></Link>)}{fieldRoles.length === 0 && <p className="p-6 text-base text-slate-500">No {roleField} roles match these filters.</p>}</div></section>; })}</div>}</main>;
}
